### ISSUE TITLE
Random images repeating after a while

### ISSUE THREAD

**Issue by gk611995** [unsplash/unsplash-js#56]
#### Observed Behaviour
When is use count>1 and any search query in random photo api,the images tend to repeat after a while.
What i expect on each api call is fresh images.Is this expected behaviour?

**Comment by irondeau** [comment]
I am experiencing similar issues with the random image API, where they tend to repeat after a short period of time (~15 images). I'm using the landscape orientation parameter which I suspect may be the root cause of the issue.

**Comment by RobCanton** [comment]
I'm getting this as well with just count>1. Not very useful if the images repeat!

**Comment by samijaber** [comment]
Tagging @unsplash/api as this is a backend issue

**Comment by bogdancojocariu** [comment]
Experiencing the same issue:
```
unsplash.photos
    .getRandomPhoto({
      query: `${query}&${Number(new Date())}`,
      count: 30, // Maximum allowed by API
    })
```
and then, in the response, I am mapping through the ids only to find out I am receiving 10 photos instead of 30 (I can create a separate issue for this).

I am making the above request periodically. The problem is that I am receiving the same 10 photos over and over again.

Thanks

**Comment by aaronklaassen** [comment]
Hey folks yeah this was a backend API issue, not one with this lib. We deployed a fix a few days ago though so ya'll should be good to go, now. :+1:

If you see similar behaviour again though feel free to let us know at api@unsplash.com

**Comment by bogdancojocariu** [comment]
Hello,

I am still experiencing the issue. I have created a codepen as a proof: 
This also exposes the issue of requesting 30 photos and only receiving 10.

https://codepen.io/airtame/pen/dwqmwb

If you exclude `query` from the request, I receive 30 photos in the response.

Thanks
